<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SysDiff.Storage</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SysDiff.Domain\SysDiff.Domain.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
</Project>
